[versions]
compileSdk = "34"
minSdk = "28"
targetSdk = "34"

coreKtx = "1.12.0"
lifecycleRuntime = "2.6.2"
activityCompose = "1.8.2"
composeBom = "2024.02.01"
ui = "1.6.4"
material3 = "1.2.1"
appcompat = "1.6.1"
constraintlayout = "2.2.1"
admob = "22.6.0"
okhttp = "4.11.0"
navigationFragmentKtx = "2.9.4"
navigationUiKtx = "2.9.4"

[plugins]
android-application = { id = "com.android.application", version = "8.11.2" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.9.25" }

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntime" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "ui" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
admob = { module = "com.google.android.gms:play-services-ads", version.ref = "admob" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

junit = { module = "junit:junit", version = "4.13.2" }
androidx-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "ui" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "ui" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
